### ISSUE TITLE
IndexError at /mess/order_list/

### ISSUE THREAD

**Issue by arynamn** [Samadeol/CS253#38]
Error when clicking recent-orders. 

Environment:

Request Method: GET
Request URL: https://digi-campus.herokuapp.com/mess/order_list/

Django Version: 4.0.4
Python Version: 3.10.3
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'Login',
 'Mess',
 'Hall',
 'rest_framework',
 'crispy_forms']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware']

Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/app/.heroku/python/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/.heroku/python/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/Mess/views.py", line 287, in order_list_view
    context[name_1[i]]=name[i]

Exception Type: IndexError at /mess/order_list/
Exception Value: list index out of range

**Comment by Samadeol** [comment]
Thank you for finding this bug

It has been resolved now :)
